[theme]
primaryColor = "#16A085"                # Bright aqua green – energetic and health-oriented
backgroundColor = "#FAFAFA"             # Soft white – bright and clean
secondaryBackgroundColor = "#E8F8F5"    # Light mint – fresh and bright side panels
textColor = "#1B2631"                   # Dark slate – strong contrast, readable
font = "sans serif"
