[theme]
primaryColor = "#2E8B57"                # SeaGreen - for buttons and highlights
backgroundColor = "#F4F6F6"             # Soft white - clean and calming
secondaryBackgroundColor = "#E8F6F3"    # Pale green-blue - for sidebar or cards
textColor = "#1C2833"                   # Deep grey - easy on the eyes
font = "sans serif"                     # Clean and modern
