[theme]
primaryColor = "#00B894"                # Bright teal - energetic but soft (buttons)
backgroundColor = "#FFFFFF"             # Pure white - clean and professional
secondaryBackgroundColor = "#F1F2F6"    # Light grey-blue - soft on the eyes (sidebar/panels)
textColor = "#2D3436"                   # Charcoal - great contrast, easy reading
font = "sans serif"                     # Modern and readable
